name: MLOps CD - Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Configure Docker for Artifact Registry'
      run: 'gcloud auth configure-docker us-central1-docker.pkg.dev' # Use your region

    - name: 'Build Docker image'
      run: 'docker build -t us-central1-docker.pkg.dev/iitm-mlops-472905/iris-api-repo/iris-api:latest .'

    - name: 'Push Docker image to Artifact Registry'
      run: 'docker push us-central1-docker.pkg.dev/iitm-mlops-472905/iris-api-repo/iris-api:latest'

    - name: 'Install gke-gcloud-auth-plugin for kubectl'
      run: 'gcloud components install gke-gcloud-auth-plugin'
      
    - name: 'Get GKE credentials'
      run: |
        gcloud container clusters get-credentials iris-api-cluster-v2 --region us-east1-b --project iitm-mlops-472905

    - name: 'Deploy to GKE'
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f hpa.yaml
        
    - name: 'Wait for deployment'
      run: |
        echo "Waiting for deployment rollout to finish..."
        kubectl rollout status deployment/iris-api-deployment --timeout=300s
        echo "Deployment successful."